language: java
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: hx8QS5dG/1ySL0LK1tEk6Ms7J8rKcuBGdK6+YacND/3LCBl3XEsZJhki/uNTfqO0jkM3MXWcbg6eP0u8Vmo9fwfIdnCh6h7yzIftH1+bPIxJ6lOQ3ZQ4v8W11H0K7k7yXY6y4kYLs2bTLC4W1SwfNTsVHzh6BfD/Fi+l9nh5Kr3IskEAtggGkY1f/TmYmvGdbuwlIL2IMF+UQ/gZZF1iERvxvuOYEk8iGrp+pEMza2uFW24MCOLDl+jnqZmtOZn2/aP8L7jFKFw6xlwSYhE5HFhHp4ovsULiwWSwC7/1e1KOKGFeHmyPhuq+fSwEtEgcWm0+Cjlv7bYRsnj5qW6XM4jLMOZbiPCcIi4y+U2UDgPAAFeeOxPPkztg88ngOtyA43l8B6zT8/rsshKdTWuRaL6kyapP4XaxIrsudU14rqxx0lSOnlunHV8tAAd5kAEWKou4lFFKL18/LFoqSB0hIzk28R2d8MIF2+ujCN1V4kBb8ekoZ16pwknOk4af5UMQckCmkxfbyX273N2GRIPDfZwDaBPgFB1XQOdQJ/YB+6Rsd5mxpJNFIYmwkqsv74GG8BgvAREOpIvBhZr5+TZ20NLwi2gKk/hSKsM77My32eH0VFL1eFpq8FBCY0bCqs2FK/6WvI22wgdTS2vnCU6REcjA87dk3D8h899CVNgv5K0=
  app: boorger
  on:
    repo: 50Cube/Boorger
