language: java
jdk:
- oraclejdk11
deploy:
  provider: heroku
  api_key:
    secure: cUWJLL0E7zoDIzrJtEdA7WQTY2C3bb6SdC9RSYA5xKkNXdZhmFVXDx9+cs+uw+exv5sVuhfRzQpxopoItzy9XctwvK3Bd7ey+3ny9mXPOy9c79bMhsOhFhI6byGHVVSL0rBFBPRCLcmIeMIcq5iX4cr1nL4/6lIjg1RZ70iHV7fo+xuBpV9Cwc6Nw8K+DI10k7MWsqaFWI4poAjak+RgY6oLlkEpgOnDFfz/hZec+aWutOOoRK6Li3VBVptjyX3tyF1nHIvI5wmmPPh9hqLS+4ernlBEgjZIHuq9HdWnVo89sQWoKscLIJLxWTRCZchrGgGfwGMdEnuO4afembzWn1Ud8PIm9yjSouJdG1sevL7YMsYfjR9TzFfowkm5Vl8ypGPxZW3H+v8Q/qcVbPPnM8tMo9xG+Ey+HKHdt+5vuBnApwJ42OvYbrzyhmMzgAeZ3+G38GukuoxS0klEVWHx45ECu09RTFGHAX0ACp8sgTPNzzXbdU1QRLOtqFOshO8WhXCWAd70MFSmUiKz0FNM6O74eg5NWm7aGtr6fWDiXYwr0B1UQvr2KenUk4ZgyZUuqxv89b7vBBwaZ32xCliY7KqFLZ3x5lTTTExzvjUwmChWukz7Arq83gnInuTI/50YE9+miZVCBKcvCJ5O6yxkLIyFXB6xnfy9UBbiLHYEAwg=
  app: boorger
  on:
    repo: 50Cube/Boorger