language: java
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: H2Lxzk4XdOYoX7QcFabud/9MvRDnYmxlzFWmfJ6ZQTx/AIOEsoPeJkd53vFHyhq7vg7LhVv3Qe4UV0obZ5xv6W5l3VtiA2WrhZXVWEMvb0eJ4V0Ifvbb9HfRskWhDv2I2Pd7KQd/O/fY1O3C+FIzb5a86E4BeuwAcOXTgL/Hp3ErCtjnpHHKrSBiWLMj3x3e/apYfeRXPIMcHkb85jPygsEVRZmhrdW4qB4MdVdOLgPdNCGsIar06sB6zP5OgYDrbdOfXh4OEHbyWkbFLK7GlkVmsWfXhrvLeIW8WaLuNhA/JFNC/VKw7Lfx7nHTb8evHxCTOivMpyg8Io49KNSCRN46GZ0HdQJ7nlk5eSsXZmW9fvFmwX06Kv7YlKkev2ea5QFl7kSBbI+z0O30d//UBTWCORK53j4yS8tU04LF/oBjEEvnrhcm5xyYilZCP3Vgacu9m685538zoSKlkK+vkGMy940AnDsbU6UdfUfdLlfLQf8JENvGjTU6XNxOQlrWB+Z8JwoqUWhFSp13KAy054P9Tn+g79I0MNBAngRhEWAWo/q11V9OTFDwmSCrieoceu3LZKvJU6fOZBMSTMe+SCPK4gIWtmVogkaCq8rt83F/9bpuUty54t7fPN4mJ1qoIcCSWjGDUZ3mNYoCUWvJYs9IE/+Nyj2pSWQP9AztgEw=
  app: boorger
  on:
    repo: 50Cube/Boorger
