language: java
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: X8WC+AcZQgPVWZP1Iy7nHzGcPecjpRh/z2beMEN4Duo1zBV4HRO0wAiy2Mgq2G2BG0KC8/lIbkdVyT2//pzbF9Qd9ccvKxySWiS6055qNXhkFAkKHn2Yv8CBbB8h0JjBCSKSMS3TxKV9GlfAjDSpg0QK6ARKwYax318MGkEV4TrY2MRccvFLCHA1Da5seJkuFJ3C7KPUxxGCpYh1wnuLe0EVWNIrRRnNo2m0uOad+c89iAUTrLSf/p7cINw8+xhX9pONWkXSEKVe+JNWJepV8Zj6/QHtqqTPFrIqYALnDv1MjOPz2ue+Jb9hWd508USTBn+Eg9kU3x0SPH02U/mMg8XBEw/EntAoEf9GVy1V7ECUSu1xq1Mp6BjiHjbWmc+0i7Tv73jiXshtLIO67EAlYjJlGGcnis+Bvmr+15BG3e7blJhaQ1MVFipahwXHR7nlJdi3mzCVZTcYm9uwn0/1aADxNKcb8NqYZCFHeZ03F8weO3C83Kwex1h0mJWeh+py3eviwu/HRa6A8zHiFxPyFGsPhBx1YUXNRuhGPkkXfdntK2gc5LiWcI0p1YWkBSj5jxM/AGbYNnOC3M9/ixK4A1pSnV6WREeHQMvqMC0GYdWm+SdQB7sKrhKtIVRkG2N9mxEpEuHwc/tZpgROXe3pktmMAUlJ0SnSJeRZY8/PWDo=
  app: boorger
  on:
    repo: 50Cube/Boorger

