language: java
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: HmgVf37jFHEqPX32CuFxojewpAopAW/NK47RVPGDF1PcEAIbNWWwRx5HESijxTJk5SSzvBeOMErCMhrjO8TNh5VsyEhQDKROt6Gszlv5FgZb9vgTc/L7HSM70y9/nAgj0sqiQZo3RKFqszKpmZ7c+WZqSZm4u1wGScoyn/hOzQGAbzKCoripDzS0EsvBTbTLc1XDddfnNEXrlV7pcuzrNl5KGL9kejyR95gXgMf6fkUlZRtyhg/WXLF0QK/HucLikpgURUeijhux43WjmEZVU61edX/ETymmjtUnCuZN4mbnowtzRgsR72Rwf1XFU6BHmQ0bIExwiHbUPwP3FUGTkIB/HrdG7AabfScBAcaIwBRZFZF9IoXnd8F4r2FRitnh3vcuMovU6o2u4lFh6BrITRquU2NdvuE0Bt8RY0yM7tL87uHTpdHx2zTPC3Oo/DLpv3uKywhdkvEQMV3oxQl/iCqgkx5+nYxECSQsK1poi/dY/hucPHYvRUCK2Za2yOcZ/zjq1V+mc0S1HuChnH3V7NyL4ZL5ALfQBOCQIyxpnIWxEmGCgnZChwobVr1noT4+pGDGlaeRoqEbLTYpBlYvND+tDLkpjFVCRmnI5NQuwF34mX70YOBnY8n5Mqfh+rQYTz64j+//XqXKpqEGp+LhpYJ1aumZEXpz2L5w8FjixOQ=
  app: boorger
  on:
    repo: 50Cube/Boorger
