language: java
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
     secure: yVQxxH+3mzAeYP6T4D20Dz7WcluCB6wyXOO0v3RA4MztCXj+5pHf0Q/noRPz8Gi+BS8k7L/KTHixLIgyYBDlxquGy4SOk62LH454BScYqd1wNla1eYis4PCKmdebhk18jzbzFvKzG293GAVggQTYANp1cC32LWCesbIDs1XuRjSC5tM3u/WCS+2g1bEwJenCLXHpLTPo6Zn78NarFju69wtdfYgE+7Uij4hZ1R2ez7A2lgh3xpMFDSTqL0qDQQmkeIqnrwgE1PZf5aarhDaI52DXhG21OTmakFdb1IvDh5m9ifixMTYxfUInrzWm/wM6ebb9qkb45JbjPxHdc5fteK2Aydtg34mSRzjsu9UkDkBWV0LXsOwXWWn3LN9Vcm8plSyNQlQIR9kaSHmJvJB+BaSPKRBGjHKyFPZFU/sbn7uRnEA4t5dx64OXHAMN9hQO+TxTFsdEJith0d954CfxDsBwRCXdbMKiSxhSFxvxGwx/sCLrmxF2ppRjuEeRdaPJOJU8Y//MVqSLbfHV9qwMQwxQ/xaB5oSnf7kQgwRpdsQ8zcloXTzJl/cxm124WKJARwjFgLwDF30ob+5IcX58QCLndY/jVy9vhmrI/M90YZF0p/3tUVn74RU/25p1leQU3l6KYe5JfjtClu0xbXYG0HkxJFB+SWdH3mKLXvinZuk=
  app: boorger
  on:
    repo: 50Cube/Boorger
